name: xcube-smos
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.10
  - click
  - fsspec
  - h5netcdf
  - h5py
  - importlib_resources
  - numpy
  - numba
  - pandas
  - requests
  - xarray
  - xcube >=1.2
  # Development
  - pytest
